# Generated by Django 5.0.6 on 2024-05-29 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='eventsTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('StartTime', models.TimeField()),
                ('EndTime', models.TimeField()),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='usersTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=150)),
                ('dateOfBirth', models.DateField()),
                ('registrationDate', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='trialTable',
        ),
        migrations.AddField(
            model_name='eventstable',
            name='attendees',
            field=models.ManyToManyField(blank=True, to='events.userstable'),
        ),
    ]
