# Generated by Django 5.0.6 on 2024-05-29 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventstable_userstable_delete_trialtable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventstable',
            name='attendees',
            field=models.ManyToManyField(blank=True, null=True, to='events.userstable'),
        ),
    ]
