# Generated by Django 5.0.6 on 2024-06-02 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usersTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=150)),
                ('dateOfBirth', models.DateField()),
                ('registrationDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='eventsTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=100)),
                ('eventDate', models.DateField()),
                ('StartTime', models.TimeField()),
                ('EndTime', models.TimeField()),
                ('capacity', models.IntegerField()),
                ('attendees', models.ManyToManyField(blank=True, null=True, to='eventure.userstable')),
            ],
        ),
    ]
