# Generated by Django 5.0.6 on 2024-06-10 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventure', '0003_rename_endtime_eventstable_endtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstable',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
