# Generated by Django 5.0.6 on 2024-06-12 16:02

import django.contrib.auth.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('eventure', '0004_userstable_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userstable',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='userstable',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='userstable',
            name='dateOfBirth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userstable',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
