# Generated by Django 5.0.6 on 2024-06-12 16:12

from django.db import migrations

def set_username_to_email(apps, schema_editor):
    User = apps.get_model('eventure', 'usersTable')
    for user in User.objects.all():
        user.username = user.email
        user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('eventure', '0005_alter_userstable_options_alter_userstable_managers_and_more'),
    ]

    operations = [
        migrations.RunPython(set_username_to_email),
    ]
