# Generated by Django 5.0.6 on 2024-06-12 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventure', '0007_userstable_date_joined_userstable_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstable',
            name='password',
            field=models.CharField(default='password', max_length=260),
        ),
    ]
